spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.161.142.98:13306/NCP_DEV?autoReconnect=true  e
#    username: ncp_dev
#    password: WkaQhd@629!!dev
    url: jdbc:mysql://localhost:3306/wever
    username: jsg
    password: qwer1234#
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect