#spring:
#  datasource:
#    somedb:
#      jdbc-url: jdbc:mysql://localhost:3306/blind?useUnicode=yes&characterEncoding=UTF-8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username:
#      password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
